// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[] args) {
	int countNumber= Integer.parseInt(args[0]);
	int biggerThen = 0;
	int smallerThen = 0;
	while (countNumber!=0)
	{
		double randomNumber = Math.random();
		if(randomNumber>0.5)
		{
			biggerThen=biggerThen+1;
		}
		else
		{
			smallerThen=smallerThen+1;
		}
	countNumber--;
	}
	if((biggerThen>0) && (smallerThen >0))
	{
	double ratio= (double) biggerThen / smallerThen;
	System.out.println("> 0.5:" + " " + biggerThen + " " + "times");
	System.out.println("<=0.5:" + " " + smallerThen + " " + "times");
	System.out.println("Ratio:" + " " + ratio);
	}
	else
	{
	System.out.println("> 0.5:" + " " + biggerThen + " " + "times");
	System.out.println("<=" + " " +"0.5:" + " " + smallerThen + " " + "times");
	}
	}	

}
	

